# Generated by Django 3.2.6 on 2021-09-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210916_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='language',
            name='Language_Pre',
        ),
        migrations.AddField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='language',
            field=models.ManyToManyField(to='app.Language'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Gender',
            field=models.CharField(max_length=15),
        ),
    ]
