# Generated by Django 3.2.6 on 2021-09-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210916_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='language',
            field=models.ManyToManyField(blank=True, to='app.Language'),
        ),
    ]
